apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gotektongithub291024 
  janus-idp.io/tekton: gotektongithub291024
  backstage.io/kubernetes-id: gotektongithub291024
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gotektongithub291024
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  