apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gotektongithub291024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gotektongithub291024 
  name: gotektongithub291024
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gotektongithub291024 
